### PR TITLE
Patch NullPointerException with WeakHashMap in TankManager

### LINKED ISSUE #28: NullPointerException with TankManager.isPartOfTank()
**FancyFluidStorage Version**: 1.12.2-2.2.4

**MinecraftForge Version**: 14.23.5.2838

**Client or Server?**:
- [ ] Client
- [X] Server

**Crash Report (via. [Pastebin](https://pastebin.com/a6YANmK4))**: https://pastebin.com/a6YANmK4

**What happens / happened?**:
Sometimes, server crash on block break event.

**How can we reproduce it?**:
Start a server with a small -xmx setting (this will make the garbage collector work more often)
Setup some quarry (the builder from rfTool can be a good choice because he break blocks very fast) in a dimension not charged by a player.

**Suspected error**:
I suspect crash append if gc run in isPartOfTank() method after getDimensionSafely() call.

### PR DESCRIPTION
**Pull request by Naheulf**
Should patch garbage collector concurrent access with WeakHashMap.
Disclamer: I did not test this code.

Should fix #28

### CODE REVIEW

**Comment by gigabit101** [comment]
Looks good to me

**Comment by Lordmau5** [comment]
Looks good to me as well :)
Seeing as it is a draft PR though, I'm gonna wait up until you feel it is actually ready to be merged in.

**Comment by Naheulf** [comment]
I marked this PR as a draft only because I did not test it. I feel it is actually ready to be merged in.

**Comment by Lordmau5** [comment]
I've actually reverted the merge. The code was straight up non-functional.

First off, [line 11](https://github.com/Lordmau5/FFS/pull/29/commits/64e488f1d0141ed35388ac30f1c40c938fc89658#diff-63a465e8f6e9595bc4e0988e26267982R11):
No type defined.

Second off, [line 15](https://github.com/Lordmau5/FFS/pull/29/commits/64e488f1d0141ed35388ac30f1c40c938fc89658#diff-63a465e8f6e9595bc4e0988e26267982R15):
Can't always instantiate `V`, so that's useless, too.

3rd, [line 40](https://github.com/Lordmau5/FFS/pull/29/commits/64e488f1d0141ed35388ac30f1c40c938fc89658#diff-63a465e8f6e9595bc4e0988e26267982R40):
Invalid equals check (Java doesn't use `===`)
___
I'm gonna try to quickly write a simple SafeWeakHashMap mockup myself that doesn't have a default constructor. Should also take care of the issue.
If that won't work I'll just go ahead and use `getOrDefault`.

**Pull request merged**
